### ISSUE TITLE
undefined reference to `yywrap'

### ISSUE THREAD

**Issue by cs-pchsu** [unfs3/unfs3#16] opened 2020-04-13 09:41 UTC
Hi,

I want to use cross compiler, arm-linux-gnueabihf-gcc, to build unfs3.
However I get the error as bellow.
unfs3/Config/lex.yy.c:980: undefined reference to `yywrap'

Is anyone here willing to provide some way to help me solve this problem?

**Comment by CendioOssman** [comment] 2020-04-13 11:02
This does ring a bell, but I'm afraid I don't remember what the issue was. I seem to recall it had something to do with the version of flex. What are you using on your system? We're using 2.5.35 here.

**Comment by cs-pchsu** [comment] 2020-04-14 01:25
Not sure which version you are referring to, unfs3 version ?

Where can I get version information ?

When I put an empty shell of yywrap, the compilation will succeed, is there a mechanism to replace this function ?

**Comment by CendioOssman** [comment] 2020-04-23 08:34
That file is generated by a command called `flex`, so I wanted to see if there might have been a change there that is the cause of this. You should be able to run `flex --version` to check what you have.

**Comment by rossburton** [comment] 2020-07-17 09:12
So this is going to happen to *everyone* when autoconf 2.70 is released as it no longer links to `libfl.so`, which provides the trivial `return 1` implementation of `yywrap()`.

The easiest/obvious fix is to add `%option noyywrap` to `Config/exports.l` alongside the other `%option` lines.

**Comment by CendioOssman** [comment] 2020-09-28 13:48
Seems reasonable. It doesn't seem like we need the `yywrap()` functionality. Fixed in 3fa0568e6ef96e045286afe18444bc28fe93962b.

**Closed by CendioOssman** 2020-09-28 13:48 UTC
